[versions]
# NOTE: Don't upgrade `com.android.tools.build:gradle` version higher than `aniyomi-extensions-lib`
agp_version = "8.2.2"
coroutines_version = "1.8.1"
kotlin_version = "2.0.0"
okhttp_version = "5.0.0-alpha.14"
serialization_version = "1.7.1"

[libraries]
gradle-agp = { module = "com.android.tools.build:gradle", version.ref = "agp_version" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }
gradle-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin_version" }
gradle-kotlinter = { module = "org.jmailen.gradle:kotlinter-gradle", version = "3.15.0" }

aniyomi-lib = { module = "com.github.komikku-app:aniyomi-extensions-lib", version = "e34cab74" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin_version" }
kotlin-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization_version" }
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization_version" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines_version" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines_version" }

injekt-core = { module = "com.github.mihonapp:injekt", version = "91edab2317" }
rxjava = { module = "io.reactivex:rxjava", version = "1.3.8" }
jsoup = { module = "org.jsoup:jsoup", version = "1.18.1" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp_version" }
quickjs = { module = "app.cash.quickjs:quickjs-android", version = "0.9.2" }
jsunpacker = { module = "dev.datlag.jsunpacker:jsunpacker", version = "1.0.1" }

[bundles]
common = ["kotlin-stdlib", "coroutines-core", "coroutines-android", "injekt-core", "rxjava", "kotlin-protobuf", "kotlin-json", "jsoup", "okhttp", "aniyomi-lib", "quickjs"]
