name: 🌐 Source request
description: Suggest a new source for Anikku
labels: [Source request]
body:

  - type: input
    id: name
    attributes:
      label: Source name
      placeholder: |
        Example: "Not Real Source"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Source link
      placeholder: |
        Example: "https://notrealsource.org"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Source language
      placeholder: |
        Example: "English"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.
        Example: "+18/NSFW = yes"

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a title with source name.
          required: true
        - label: I have checked that the extension does not already exist on the [website extensions list](https://anikku-app.github.io/extensions/) or the app.
          required: true
        - label: I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/yuzono/aniyomi-extensions/) and verified it does not appear in the code base.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true

  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Is this issue important to you?"
      description: |
        **Please do not modify this text area!**

        This template lets users vote with a :+1: reaction if they find it important.
        This is not a guarantee that highly-requested issues will be fixed first, but it helps us to figure out what's important to users. Please react on other users' issues if you find them important.
      value: |
        Add a :+1: [reaction] to [issues you find important].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you find important]: https://github.com/yuzono/aniyomi-extensions/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
