package eu.kanade.tachiyomi.multisrc.wcotheme

import eu.kanade.tachiyomi.animesource.model.AnimeFilter

object Filters {

    class GenresFilter() : UriPartFilter(
        "Browse by Genre",
        arrayOf(
            Pair("<select>", ""),
            Pair("Absurdist humor", "69"),
            Pair("Action", "14"),
            Pair("Action comedy", "222"),
            Pair("Adapted Literature", "181"),
            Pair("Adult animation", "72"),
            Pair("Adult Cartoons", "141"),
            Pair("Adult puppeteering", "217"),
            Pair("Adventure", "4"),
            Pair("Alternate History", "49"),
            Pair("Animal Adventure", "236"),
            Pair("Animated", "23"),
            Pair("Animated sitcom", "168"),
            Pair("Animated television series", "66"),
            Pair("Animation", "125"),
            Pair("Anime", "230"),
            Pair("Anthology series", "79"),
            Pair("Artificial Intelligence", "231"),
            Pair("Avant Garde", "225"),
            Pair("Baseball", "98"),
            Pair("Biography", "221"),
            Pair("Black comedy", "166"),
            Pair("Boys Love", "227"),
            Pair("Car racing", "88"),
            Pair("Cars", "209"),
            Pair("Cartoon series", "142"),
            Pair("Chanbara", "89"),
            Pair("Children's fiction", "204"),
            Pair("Children's television series", "67"),
            Pair("Chinese Cartoon", "119"),
            Pair("Comedy", "6"),
            Pair("Comedy horror", "216"),
            Pair("Comedy-drama", "211"),
            Pair("Comic science fiction", "176"),
            Pair("Coming-of-age story", "104"),
            Pair("Computer Animation", "232"),
            Pair("Conspiracy thriller", "235"),
            Pair("Contemporary fantasy", "140"),
            Pair("Crime", "55"),
            Pair("Cringe comedy", "220"),
            Pair("Cutaway gag humor", "85"),
            Pair("Cyberpunk", "75"),
            Pair("Dark Fantasy", "44"),
            Pair("Dark humor", "70"),
            Pair("Deadpan", "87"),
            Pair("Dementia", "208"),
            Pair("Demons", "111"),
            Pair("Detective Fiction", "61"),
            Pair("Documentary", "133"),
            Pair("Drama", "16"),
            Pair("Drug Crime", "233"),
            Pair("Dystopian", "57"),
            Pair("Ecchi", "102"),
            Pair("Educational", "128"),
            Pair("Edutainment", "80"),
            Pair("Epic", "226"),
            Pair("Erotica", "237"),
            Pair("Espionage", "81"),
            Pair("Family", "123"),
            Pair("Family television series", "68"),
            Pair("Fantasy", "8"),
            Pair("Fighter", "65"),
            Pair("Football", "134"),
            Pair("Friendship", "100"),
            Pair("Game", "93"),
            Pair("Game-Show", "170"),
            Pair("Girls Love", "223"),
            Pair("Girls With Guns", "51"),
            Pair("Goth", "90"),
            Pair("Gourmet", "224"),
            Pair("Graphic novel", "137"),
            Pair("Harem", "28"),
            Pair("Harold and the Purple Crayon", "202"),
            Pair("High School", "38"),
            Pair("Historical", "56"),
            Pair("Historical Fantasy", "45"),
            Pair("History", "147"),
            Pair("Horror", "20"),
            Pair("Horror comedy", "159"),
            Pair("Idol anime", "105"),
            Pair("Isekai", "210"),
            Pair("Josei", "206"),
            Pair("Kids", "96"),
            Pair("Learning", "135"),
            Pair("Magic", "48"),
            Pair("Magical boy", "94"),
            Pair("Magical Girl", "31"),
            Pair("Manga", "99"),
            Pair("Martial Arts", "37"),
            Pair("Mecha", "35"),
            Pair("Mecha 2", "32"),
            Pair("Metafiction", "59"),
            Pair("Military", "34"),
            Pair("Movie", "121"),
            Pair("Music", "43"),
            Pair("Musical", "129"),
            Pair("Musical comedy", "215"),
            Pair("Mystery", "12"),
            Pair("Mythic fiction", "113"),
            Pair("Occult", "62"),
            Pair("Off-color humor", "143"),
            Pair("Parody", "39"),
            Pair("Police", "60"),
            Pair("Political satire", "218"),
            Pair("Post-Apocalyptic", "42"),
            Pair("Pre-School", "136"),
            Pair("Psychological", "30"),
            Pair("Racing", "229"),
            Pair("Reverse Harem", "107"),
            Pair("Role-playing", "33"),
            Pair("Romance", "22"),
            Pair("Romantic Comedy", "27"),
            Pair("Romantic Drama", "54"),
            Pair("Samurai", "106"),
            Pair("Satire", "78"),
            Pair("School", "53"),
            Pair("School Dormitory", "101"),
            Pair("Sci-fi", "50"),
            Pair("Science Fantasy", "36"),
            Pair("Science Fiction", "10"),
            Pair("Seinen", "103"),
            Pair("Senryuu Girl", "214"),
            Pair("Short", "120"),
            Pair("shoujo", "97"),
            Pair("Shoujo Ai", "116"),
            Pair("Shounen", "95"),
            Pair("Shounen Ai", "115"),
            Pair("Sitcom", "77"),
            Pair("Situation comedy", "178"),
            Pair("Sketch comedy", "205"),
            Pair("Slapstick", "117"),
            Pair("Slice Of Life", "25"),
            Pair("Social satire", "163"),
            Pair("Space", "114"),
            Pair("Space Opera", "41"),
            Pair("Splatter", "86"),
            Pair("Sports", "29"),
            Pair("Spy fiction", "203"),
            Pair("Steampunk", "58"),
            Pair("Stop Motion", "157"),
            Pair("Superhero", "74"),
            Pair("Superhero fiction", "149"),
            Pair("Supernatural", "26"),
            Pair("Superpower", "47"),
            Pair("Surreal", "118"),
            Pair("Surreal humor", "71"),
            Pair("Surrealism", "82"),
            Pair("Surrealist Comedy", "18"),
            Pair("Suspense", "76"),
            Pair("Sword and sorcery", "155"),
            Pair("Talk-Show", "228"),
            Pair("Teen Animation", "83"),
            Pair("Teen Drama", "73"),
            Pair("Thriller", "24"),
            Pair("Toilet humor", "219"),
            Pair("Toilet humour", "84"),
            Pair("Tournament", "52"),
            Pair("Tragedy", "63"),
            Pair("Urban", "108"),
            Pair("Urban Adventure", "234"),
            Pair("Urban fantasy", "112"),
            Pair("Vampire", "110"),
            Pair("Virtual Reality", "40"),
            Pair("War", "109"),
            Pair("Western", "172"),
            Pair("Yaoi", "132"),
            Pair("Yuri", "46"),
        ),
    )

    open class UriPartFilter(displayName: String, private val vals: Array<Pair<String, String>>) :
        AnimeFilter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
        fun toUriPart() = vals[state].second
        fun isEmpty() = vals[state].second == ""
        fun isDefault() = state == 0
    }
}
